Added missing pageRefUtils
Missing line caused:
error: Action failed: c:navigateEverywhereLFA$controller$invoke [Cannot read properties of undefined (reading 'encodeDefaultFieldValues')]